name: Zola Deploy

on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout'
        uses: actions/checkout@master
      - name: 'Build'
        uses: shalzz/zola-deploy-action@master
        env:
          BUILD_DIR: .
          BUILD_ONLY: true
      - uses: actions/upload-artifact@v2
        with:
          name: github-pages
          path: public/
  deploy:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      id-token: 'write'
      pages: 'write'
    steps:
      - name: 'Deploy'
        uses: actions/deploy-pages@v1-beta
