name: Zola Deploy

on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout'
        uses: actions/checkout@master
      - name: 'Build'
        uses: shalzz/zola-deploy-action@master
        env:
          BUILD_DIR: .
          BUILD_ONLY: true
      - uses: alehechka/upload-tartifact@v1
        with:
          name: github-pages
          path: -C public .
  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.pages.outputs.result }}
    permissions:
      id-token: 'write'
      pages: 'write'
    steps:
      - name: Get Pages
        id: pages
        uses: actions/github-script@v5
        with:
          result-encoding: string
          script: |
            const pages = await github.rest.repos.getPages({
              owner: context.repo.owner,
              repo: context.repo.repo,
            });
            return pages.data.html_url;
      - name: 'Deploy'
        uses: actions/deploy-pages@v1-beta
