name: Zola Deploy

on:
  workflow_call:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout'
        uses: actions/checkout@master
      - name: 'Build'
        uses: shalzz/zola-deploy-action@master
        env:
          BUILD_DIR: .
          BUILD_ONLY: true
      - name: Tar files
        run: tar -cvf artifact.tar -C public .
      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: github-pages
          path: artifact.tar
  deploy:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      id-token: 'write'
      pages: 'write'
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: 'Deploy'
        id: deployment
        uses: actions/deploy-pages@v1-beta
